### ISSUE TITLE
Move log under /var/log/solr/ directory

### ISSUE THREAD

**Issue by aperepel** [abajwa-hw/solr-stack#1]
Anticipating multiple Solr servers running per node.
Any Hadoop-integrated component in HDP follows the /var/log/_service_name_/multiple_log_files here
This will also help with grouping any additional logs coming out of the stack.

**Comment by abajwa-hw** [comment]
This is fixed in current version. 
$ ls /var/log/solr
solr-6083-console.log  solr_gc.log  solr-install.log
