### ISSUE TITLE
Link/output actual server logs into /var/log/solr/ directory

### ISSUE THREAD

**Issue by aperepel** [abajwa-hw/solr-stack#3]
Related to #1 - I found the actual useful logs to be in $SOLR_HOME/server/logs. Link/output those logs into the /var/log/solr/ directory, where users expect them. Can still keep the solr.log file that is written today by the stack, just rename it - it only provides a few lines output about startup success/failure and PID.

**Comment by abajwa-hw** [comment]
This is fixed in the current version
