### ISSUE TITLE
Documentation Request - example create collection

### ISSUE THREAD

**Issue by alexmc6** [abajwa-hw/solr-stack#7]
Would it be possible to add a simple collection creation command into the documentation - along with the expected results. So for example I tried

[solr@ambari1 solr-5.3.0]$ pwd
/opt/solr/solr-5.3.0
[solr@ambari1 solr-5.3.0]$ whoami
solr
[solr@ambari1 solr-5.3.0]$ bin/solr create_collection -c collection2

ERROR: Error loading config name for collection collection1

I don't know whether collection1 is something I did wrong earlier, or whether it is a bug in the config. There is so much documentation out there for solr v4 and earlier :-(

**Comment by alexmc6** [comment]
I should add to this that it seems to think collection1 exists - but does not think it is working... eg 

[solr@ambari1 latest]$ bin/solr healthcheck -c collection1
ERROR - 2016-07-13 12:23:46.545; org.apache.solr.client.solrj.impl.CloudSolrClient; Request to collection collection1 failed due to (510) org.apache.solr.common.SolrException: Could not find a healthy node to handle the request., retry? 0

ERROR: Could not find a healthy node to handle the request.

[solr@ambari1 latest]$ bin/solr healthcheck -c doesnotexist

ERROR: Collection doesnotexist not found!

[solr@ambari1 latest]$

**Comment by abajwa-hw** [comment]
@alexmc6 have added the README to include sample command to create collection. Also included links to some tutorials

**Comment by alexmc6** [comment]
Thanks. Much appreciated. 

Incidentally I think the problem for me was that somehow my ZooKeeper got incomplete SolR setup. I then told SolR to use a brand new location in ZooKeeper (/solr2 instead of /solr) and it magically started to work.

**Comment by NitishShanbhag** [comment]
@alexmc6  How do you set solr location in zookeeper ??
