### ISSUE TITLE
How does this relate to the lucidworks fork?

### ISSUE THREAD

**Issue by alexmc6** [abajwa-hw/solr-stack#8]
We have a fork of this being done by lucidworks. Would you say that this is still the best version to use? There are several changes you have made here which LucidWorks have not merged into their code, and vice versa.

In partiular it is not clear to me how to uninstall this once installed - eg so that I can try the other solr ambari stack

**Comment by abajwa-hw** [comment]
@alexmc6 that's a valid question. This started as a demo project to help LW team build the official integration for the product, but it hasn't been incorporated yet. 
You should be able to easily uninstall one and try the other by following the instructions below:
https://github.com/abajwa-hw/solr-stack#remove-solr-service

note this only unregisters the service from Ambari but does not delete the install bits/rpm: you would need to do that manually

**Comment by alexmc6** [comment]
really helpful. thanks.
